name: "Test Suite"

on:
  pull_request:
  push:
    branches:
      - "6.x"
  schedule:
    - cron:  '0 8 * * *'

jobs:
  tests:
    name: "Tests ${{ matrix.php-version }} ${{ matrix.dependencies }} (Symfony ${{ matrix.symfony-version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "8.3"
          - "8.4"
          - "8.5"
        symfony-version:
          - "5.4.*"
          - "6.4.*"
          - "7.3.*"
          - "7.4.*"
          - "8.0.*"
        exclude:
          - php-version: 8.3
            symfony-version: "8.0.*"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: flex, composer:v2

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-composer-

      - name: "Configure Symfony"
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "composer test"

  static-analyze:
    name: "Static Analyze"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          php-version: "8.3"
          ini-values: memory_limit=-1
          tools: composer:v2

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-8.3-composer-${{ hashFiles('**/composer.json **/composer.lock') }}"
          restore-keys: |
            php-8.3-composer-

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Static Analyze"
        run: "composer static:analyze"

  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          tools: composer:v2
          php-version: "8.3"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v4"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-8.3-composer-${{ hashFiles('**/composer.json **/composer.lock') }}"
          restore-keys: |
            php-8.3-composer-

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Mutation Tests"
        run: "composer test:mutation"
